### PR TITLE
Rstudio server 1.3

### PR DESCRIPTION
**Pull request by randy3k**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-base/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-base/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

requires #28

### CODE REVIEW

**Comment by jonkeane** [comment]
Hello, thanks for this PR, using it I managed to get rstudio server 1.3 installed. I've been trying to get my own fork passing the CI, but there appears to be some turbulence on the linux builds recently that is preventing the builds from passing there, : https://discourse.brew.sh/t/r-icu4c-on-linux/7946 (though adding r to the tap such that it builds does build successfully on macOS and Linux with the exception audit error about linking to a shims directory: https://github.com/jonkeane/homebrew-base/actions/runs/122100449)

One thing I did have to do in order to compile rstudio-server against 4.0 was to add the following patch:

```
patch :p1 do
  url "https://github.com/rstudio/rstudio/commit/3fb2397.diff?full_index=1"
  sha256 "4f7299400c584f6262a7ecdde718e9b72767e7aa4ba6762929d3ec3db773c6c7"
end
```

I've also cleaned up some of the style errors I got. The code I've gotten to work is at https://github.com/jonkeane/homebrew-base and I can submit a PR from that if that's preferable to updating @randy3k this one)

**Comment by randy3k** [comment]
@jonkeane
Thanks for the patch. I have updated the formula.

**Comment by jonkeane** [comment]
One more bit I forgot to mention in my comment earlier, I also had to add `https://github.com/jonkeane/homebrew-base/blob/master/Formula/rstudio-server.rb#L111` to avoid `error: no member named 'isnormal' in namespace 'std'; did you mean simply 'isnormal'` and the like.

I've also submitted https://github.com/Homebrew/linuxbrew-core/pull/20473 to linuxbrew to have the r bottles re-built to hopefully resolve the issues I was seeing on linux

**Comment by jonkeane** [comment]
Ok, https://github.com/Homebrew/linuxbrew-core/pull/20473 has been merged in upstream

**Comment by randy3k** [comment]
I tested on my macOS and the homebrew docker image and it worked on both.

**Comment by jonkeane** [comment]
Are you able to re-trigger GH Actions build on linux? I'm curious if the PR for building R on linux fixes those issues.

**Comment by randy3k** [comment]
On macOS, the only issue is the style error of `cite.rb`. On Linux, there is a setup error of linuxbrew.

**Pull request closed without merging**
