### PR TITLE
Rstudio server

### PR DESCRIPTION
**Pull request by randy3k**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-base/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-base/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

it depends on #4

### CODE REVIEW

**Comment by randy3k** [comment]
The Linux build failed because 
```
Use `depends_on :java` to set JAVA_HOME
```
However, we really need this because
```
depends_on :java => "1.8"
```
doesn't set `JAVA_HOME` correctly, see https://github.com/Homebrew/homebrew-science/pull/6393 and https://github.com/Linuxbrew/brew/issues/509

**Comment by randy3k** [comment]
@sjackman, any thoughts?

**Comment by sjackman** [comment]
Let's patch Linuxbrew/brew and fix this bug. [`possible_javas`](https://github.com/Linuxbrew/brew/blob/dfc4c38491e5201f7191cfc87c70a76a86ca805c/Library/Homebrew/requirements/java_requirement.rb#L64) in `requirements/java_requirement.rb` currently checks only the formula `jdk`. It needs to be modified to also check for the formula `jdk@8`. Would you like to take a shot at making this change and submitting a PR?

**Comment by randy3k** [comment]
Thanks for asking. It may be easier for someone who are have more experience with Linuxbrew to fix it (plus I don’t own a Linux machine and I don’t want to spin up virtual box :-) )

**Comment by sjackman** [comment]
I use [Docker for macOS](https://docs.docker.com/docker-for-mac/install/) myself when I need to use Linux on macOS. I'll try to find time this week to look into it.

Another option would be to merge this PR as-is with support for macOS but not Linux, and then fix Linux later. Would you prefer to do that, or wait for Linux?

**Comment by randy3k** [comment]
Let's wait then. At least the presence if this PR would remind us that java requirement has to be patched.

**Comment by sjackman** [comment]
Fixing the `possible_javas` issue is a good first-issue for contributing to Homebrew / Linuxbrew, if you're interested in giving it a go. I can help walk you through it. No worries if not.

**Comment by sjackman** [comment]
Some `brew audit` failures to address. Sort the dependencies alphabetically, build dependencies first (as I recall, run `brew audit` locally to confirm).
```
  * C: 19: col 3: dependency "cmake" (line 19) should be put before dependency "r" (line 18)
  * C: 20: col 3: dependency "gcc" (line 20) should be put before dependency "r" (line 18)
  * C: 21: col 3: dependency "ant" (line 21) should be put before dependency "r" (line 18)
  * C: 22: col 3: dependency "openssl" (line 22) should be put before dependency "r" (line 18)
  * Formulae should not have a `HEAD` or `devel` spec
```

**Comment by randy3k** [comment]
I forgot to include `jdk@8` on `CIRCLECI`

```
  if OS.linux?
    if ENV["CIRCLECI"]
      depends_on "jdk@8" => :build
    end
  end
```

**Comment by randy3k** [comment]
> The default version of JDK is still version 9. Is this the error that you would expect from using Java 9? There's a PR to add openjdk 8 to Linuxbrew. Would you expect that to resolve this issue?
Linuxbrew/homebrew-core#8977

Ya, it is the error when using java 9.

**Comment by sjackman** [comment]
Use `&&`:
```ruby
  if OS.linux? && ENV["CIRCLECI"]
    depends_on "jdk@8" => :build
  end
```
JDK 9 as the default Java on Linuxbrew has caused some grief. Once the above PR is merging, I'm considering switching the default Java to OpenJDK 8. Sound good?

**Comment by randy3k** [comment]
Thank for the suggestion, but actually, it is what I specified.
```
  if OS.linux?
    if ENV["CIRCLECI"]
      depends_on "jdk@8" => :build
    end
    depends_on "patchelf" => :build
    depends_on "libedit"
    depends_on "ncurses"
    depends_on "util-linux" # for libuuid
    depends_on "linuxbrew/extra/linux-pam"
  end
```

OpenJDK8 sounds good. Though I dont know if rstudio server could be built with openjdk.

**Comment by sjackman** [comment]
```
  * Formulae should not have a `HEAD` or `devel` spec
```
https://circleci.com/gh/brewsci/homebrew-base/78

You'll need to remove `head` for now. It can be added back in later.

**Comment by randy3k** [comment]
It's odd. It used to build with travis-ci. Maybe due to the version of java shipped with travis? I even tried to install jdk@8, but it still doesn't work, maybe it is still picking up the system java 8?

**Comment by sjackman** [comment]
Here's the build errors on TravisCI: https://travis-ci.org/brewsci/homebrew-base/builds/420238236#L8315
TravisCI failing is not critical though. The bottles are built on CircleCI. I'm happy with this PR! It can be merged after this build of CI passes.

**Comment by sjackman** [comment]
macOS failed for looks like network connectivity issues. I can restart it after Linux completes.
```
==> Downloading https://homebrew.bintray.com/bottles/r-3.5.1.sierra.bottle.tar.gz
curl: (56) SSLRead() return error -9806
```
https://circleci.com/gh/brewsci/homebrew-base/86

**Comment by randy3k** [comment]
The travis build actually passed, only the brew audit failed because of connectivity. It makes me happy now.
```
[34m==>[0m [1mbrew audit brewsci/base/rstudio-server --online --new-formula[0m
[34m==>[0m [1mInstalling or updating 'rubocop' gem[0m
Building native extensions.  This could take a while...
Successfully installed jaro_winkler-1.5.1
Successfully installed parallel-1.12.1
Successfully installed ast-2.4.0
Successfully installed parser-2.5.1.2
Successfully installed powerpack-0.1.2
Successfully installed rainbow-3.0.0
Successfully installed ruby-progressbar-1.10.0
Successfully installed unicode-display_width-1.4.0
Successfully installed rubocop-0.57.2
9 gems installed
[31mError:[0m GitHub API Error: API rate limit exceeded for 35.224.112.202. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
Try again in 6 minutes 39 seconds, or create a personal access token:
  [4mhttps://github.com/settings/tokens/new?scopes=gist,public_repo&description=Homebrew[24m
and then set the token as: export HOMEBREW_GITHUB_API_TOKEN="your_new_token"
travis_time:end:9a440cc1,start=1535142087000000000,finish=1535142094000000000,duration=7000000000
travis_fold:end:brew.audit.12
==> [1m[31mFAILED[0m[0m
```

**Comment by sjackman** [comment]
The build on macOS was incomplete, so I tried to trigger a rebuild but messed it up. Give me a sec.

**Comment by sjackman** [comment]
Argh. GitHub closed this PR because I bungled it. Could you please open a new PR? Sorry for the hassle, Randy.

**Comment by randy3k** [comment]
No problem. Opened a new PR.

**Comment by sjackman** [comment]
Superseded by https://github.com/brewsci/homebrew-base/pull/5

**Pull request closed without merging**
