### PR TITLE
boost-rstudio-server: build new bottle

### PR DESCRIPTION
**Pull request by randy3k**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-base/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-base/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by randy3k** [comment]
@sjackman  `collect-bottles` still fails.

**Comment by sjackman** [comment]
You'll need to rebase this PR onto `origin/master`. It's currently based on 4c4ece645a59c12844efbd0b340d9e4db016ad75.

**Comment by randy3k** [comment]
my bad, it is fixed now.

**Comment by sjackman** [comment]
No worries, Randy. Merged. Thanks again for your contribution to Brewsci/base.

**Comment by randy3k** [comment]
The bottle for Mac is now sierra only? It used to be sierra or later.

**Comment by sjackman** [comment]
`_or_later` is the default now, so it's still Sierra or later.

**Pull request closed without merging**
