### PR TITLE
rstudio-server: Update to 1.2.1335

### PR DESCRIPTION
**Pull request by randy3k**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-base/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-base/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by randy3k** [comment]
@sjackman 
Any idea why the task `collect-bottles` fails?

**Comment by sjackman** [comment]
Yes. I've hopefully fixed it in PR https://github.com/brewsci/homebrew-base/pull/15.
Can you try rebasing this PR onto `master`?

**Comment by randy3k** [comment]
The linux build was killed because the container was out of memory. Setting
```
ENV["MAKEFLAGS"] = "-j1" if ENV["CIRCLECI"] || ENV["TRAVIS"]
```
is not enough.

We might need to checkout https://circleci.com/blog/how-to-handle-java-oom-errors/ for a possible solution.

**Comment by sjackman** [comment]
```
[ 19%] Building CXX object src/cpp/core/CMakeFiles/rstudio-core.dir/http/SocketProxy.cpp.o
     [java]    Compiling 4 permutations
     [java]       Process output
     [java]          [ERROR] Picked up _JAVA_OPTIONS:  -Duser.home=/root/.cache/Homebrew/java_cache
     [java]       Compiling permutation 0...
[ 19%] Building CXX object src/cpp/core/CMakeFiles/rstudio-core.dir/http/URL.cpp.o

BUILD FAILED
/tmp/rstudio-server-20190420-13021-uh82jl/rstudio-1.2.1335/src/gwt/build.xml:110: Java returned: 137

Total time: 1 minute 32 seconds
src/gwt/CMakeFiles/gwt_build.dir/build.make:57: recipe for target 'gwt_build' failed
make[2]: *** [gwt_build] Error 137
CMakeFiles/Makefile2:111: recipe for target 'src/gwt/CMakeFiles/gwt_build.dir/all' failed
```
https://circleci.com/gh/brewsci/homebrew-base/141

**Comment by sjackman** [comment]
You could use Docker for macOS (if you have a macOS laptop) or create a VM instance with only 4 GB of RAM available to replicate this issue locally, which would aid in troubleshooting.

**Comment by randy3k** [comment]
It seems that it was caused by the recent change in `circleci.yml`
https://github.com/brewsci/homebrew-base/blob/a975c2dde4d16fbdddd6c197c7c6b182711bb408/.circleci/config.yml#L10

Perhaps `HOMEBREW_MAKE_JOBS` has higher precedence than `MAKEFLAGS`. Setting it to `HOMEBREW_MAKE_JOBS` seems working.

**Comment by sjackman** [comment]
The default value of `HOMEBREW_MAKE_JOBS` was previously 32, and it was reduced to 4. Setting `MAKEFLAGS` in the formula should have higher precedence than `HOMEBREW_MAKE_JOBS`. If setting `HOMEBREW_MAKE_JOBS` allows it to build successfully though, then good enough for me.

**Comment by randy3k** [comment]
It still doesn't work on circleci. I tried locally via docker with only 2G memory and it worked. Really not sure why circleci killed the task.

**Comment by randy3k** [comment]
@sjackman I don't have more time to debug the memory issue of the linux build. Perhaps we should merge it as is?

**Comment by sjackman** [comment]
```
[ 16%] Building CXX object src/cpp/core/CMakeFiles/rstudio-core.dir/json/spirit/json_spirit_reader.cpp.o
     [java]    Compiling 4 permutations
…
     [java] 	at java.lang.Thread.run(Thread.java:748)
```
I have no experience with GWT. My guess is that it's launching multiple parallel `java` processes. It looks like setting the GWT `localWorkers` parameter could be used to reduce the number of parallel tasks.
See https://stackoverflow.com/questions/1011863/how-do-i-speed-up-the-gwt-compiler
and https://josephmarques.wordpress.com/2010/07/30/gwt-compilation-performance/

**Comment by randy3k** [comment]
Tried the localWorkers thing and it didn’t work. I guess I will leave it as is now.

**Comment by sjackman** [comment]
You could add `depends_on :macos if ENV["CIRCLECI"]` if you'd like to merge it as is. Please add a comment as to why if so.

**Comment by randy3k** [comment]
@sjackman
It’s ready.

**Comment by sjackman** [comment]
Merged. Thanks again for your contribution to Brewsci/base! 🌠

**Pull request closed without merging**
