### PR TITLE
shiny-server 1.5.13.944

### PR DESCRIPTION
**Pull request by randy3k**
- [x] Have you followed the [guidelines for contributing](https://github.com/brewsci/homebrew-base/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/brewsci/homebrew-base/pulls) for the same formula update/change?
- [x] Have you built your formula locally with `brew install --build-from-source FORMULA`, where `FORMULA` is the name of the formula you're submitting?
- [x] Does your build pass `brew audit --strict FORMULA` (after doing `brew install FORMULA`)?

-----

### CODE REVIEW

**Comment by randy3k** [comment]
@sjackman it seems that there are somethings wrong with the builds.

**Comment by sjackman** [comment]
I've opened PR https://github.com/brewsci/homebrew-base/pull/23 to remove CircleCI and add GitHub Actions. There seems to be an outage of GitHub Actions right now though.

**Comment by sjackman** [comment]
I've merged PR https://github.com/brewsci/homebrew-base/pull/23 `Add GitHub Actions`. Could you please rebase this PR onto `origin/develop`?

**Comment by sjackman** [comment]
The default branch of this repo is now `develop`. Please run `git remote set-head origin -a` in you working copy.

**Comment by randy3k** [comment]
I have rebased it on develop.

**Comment by randy3k** [comment]
> For reasons related to the GitHub Actions bottling workflow, the default branch of this repo is now `develop`. Please run `git remote set-head origin -a` in your working copy.

Got you.

**Comment by sjackman** [comment]
```
-- Installing: /home/linuxbrew/.linuxbrew/Cellar/shiny-server/1.5.13.944/shiny-server/GIT_VERSION
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ rb_sysopen - /home/linuxbrew/.linuxbrew/etc/shiny-server/.shiny-server.conf.default20200326-16970-11ty2er
==> FAILED
```
https://github.com/brewsci/homebrew-base/pull/22/checks?check_run_id=537236454#step:6:10912

**Comment by sjackman** [comment]
```
Error: 1 problem in 1 formula detected
  * Formulae should not require patches to build. Patches should be submitted and accepted upstream first.
```
I thought that this audit should only apply to new formulae. You can ignore this error for now.
https://github.com/brewsci/homebrew-base/pull/22/checks?check_run_id=537236454#step:6:10924

**Comment by randy3k** [comment]
`shiny-server` indeed is a new formula.

**Comment by sjackman** [comment]
> `shiny-server` indeed is a new formula.

Ah, right. Currently the red CI prevents merging the PR. You could use `inreplace` instead of `patch`, but looking at the patch, that doesn't seem like much fun. We can probably hack around the failure, if that failed audit is that last thing holding back this PR, with something like `brew test-bot || true` to ignore the failed status, and then it won't come up next time when it's no longer a new formula.

**Comment by sjackman** [comment]
Best case of course is if the upstream authors would incorporate some kind of build time flag to implement the desired behaviour in the build system.

**Comment by randy3k** [comment]
An odd error for linux bottle: 

```
##[error]Unable to process command '::add-matcher::brew-audit.json' successfully.
##[error]Could not find file '/home/runner/work/homebrew-base/homebrew-base/brew-audit.json'.
```

Other than that, I believe that the PATCH is the only blocker.

**Comment by sjackman** [comment]
I'll address that `brew-audit.json` error, then we can figure out a workaround for `patch`.

**Comment by sjackman** [comment]
@jonchang Do you have any insight on this error?
```
##[error]Unable to process command '::add-matcher::brew-audit.json' successfully.
##[error]Could not find file '/home/runner/work/homebrew-base/homebrew-base/brew-audit.json'.
```
https://github.com/brewsci/homebrew-base/pull/22/checks?check_run_id=537386534#step:5:32

**Comment by jonchang** [comment]
See https://github.com/Homebrew/homebrew-test-bot/pull/339

**Comment by sjackman** [comment]
@randy3k Until this issue is resolved, you can in this PR delete the line `- uses: jonchang/audit-action@master`.

**Comment by randy3k** [comment]
@sjackman I have removed the line of `jonchang/audit-action` and applied the hack that you mentioned earlier.

**Comment by sjackman** [comment]
Merged. Thanks again for your contribution to Brewsci/base, Randy!

**Pull request merged**
